## static_territories
UPDATE static_territories SET tr_name_ua='Африка' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_ua='Океанія' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_ua='Північна і Південна Америка' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_ua='Азія' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_ua='Європа' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_ua='Східна Азія' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_ua='Південно-східна Азія' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_ua='Центральна Азія' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_ua='Західна Азія' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_ua='Південна Європа' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_ua='Східна Європа' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_ua='Північна Європа' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_ua='Західна Європа' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_ua='Південна Америка' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_ua='Центральна Америка' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_ua='Північна Америка' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_ua='Карибський басейн' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_ua='Західна Африка' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_ua='Східна Африка' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_ua='Північна Африка' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_ua='Центральна Африка' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_ua='Південна частина Африки' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_ua='Австралія і Нова Зеландія' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_ua='Меланезія' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_ua='Мікронезія' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_ua='Полінезія' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_ua='Південна Азія' WHERE tr_iso_nr='34';


## static_countries
UPDATE static_countries SET cn_short_ua='Андорра' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_ua="Об\'єднані Арабські Емірати" WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_ua='Афганістан' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_ua='Антігуа і Барбуда' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_ua='Ангилья' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_ua='Албанія' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_ua='Вірменія' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_ua='Нідерландські Антіли' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_ua='Ангола' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_ua='Антарктида' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_ua='Аргентина' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_ua='Американське Самоа' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_ua='Австрія' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_ua='Австралія' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_ua='Аруба' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_ua='Азербайджан' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_ua='Боснія і Герцеговина' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_ua='Барбадос' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_ua='Бангладеш' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_ua='Бельгія' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_ua='Буркина-Фасо' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_ua='Болгарія' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_ua='Бахрейн' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_ua='Бурунді' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_ua='Бенін' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_ua='Бермуди' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_ua='Бруней-даруссалам' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_ua='Болівія' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_ua='Бразилія' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_ua='Багами' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_ua='Бутан' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_ua='Острів Буве' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_ua='Ботсвана' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_ua='Білорусь' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_ua='Беліз' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_ua='Канада' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_ua='Кокосові (Килінг) острови' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_ua='Конго' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_ua='Центрально-африканська Республіка' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_ua='Конго' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_ua='Швейцарія' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_ua="Кот д'Івуар" WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_ua='Острови Кука' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_ua='Чілі' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_ua='Камерун' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_ua='Китай' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_ua='Колумбія' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_ua='Коста-Ріка' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_ua='Сербія і Черногорія' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_ua='Куба' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_ua='Кабо-Верде' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_ua='Острів Різдва' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_ua='Кіпр' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_ua='Чеська Республіка' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_ua='Німеччина' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_ua='Джібуті' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_ua='Данія' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_ua='Доміника' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_ua='Домініканська Республіка' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_ua='Алжир' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_ua='Еквадор' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_ua='Естонія' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_ua='Єгипет' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_ua='Західна Сахара' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_ua='Еритрея' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_ua='Іспанія' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_ua='Ефіопія' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_ua='Фінляндія' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_ua='Фіджі' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_ua='Фолклендські острови' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_ua='Мікронезія, федеральні штати' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_ua='Фарерськіє острови' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_ua='Франція' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_ua='Габон' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_ua='Сполучене Королівство' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_ua='Гренада' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_ua='Грузія' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_ua='Французька Гвіана' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_ua='Гана' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_ua='Гібралтар' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_ua='Гренландія' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_ua='Гамбія' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_ua='Гвінея' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_ua='Гваделупа' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_ua='Екваторіальна Гвінея' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_ua='Південна джорджія і Південні Сандвічеви острови' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_ua='Греція' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_ua='Гватемала' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_ua='Гуам' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_ua='Гвінея-Бісау' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_ua='Гайана' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_ua='Гонконг' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_ua='Острів Херд і острови Макдональд' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_ua='Гондурас' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_ua='Хорватія' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_ua='Гаїті' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_ua='Венгрія' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_ua='Індонезія' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_ua='Ірландія' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_ua='Ізраїль' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_ua='Індія' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_ua='Британська територія в Індійському океані' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_ua='Ірак' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_ua='Іран' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_ua='Ісландія' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_ua='Італія' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_ua='Ямайка' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_ua='Йорданія' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_ua='Японія' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_ua='Кенія' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_ua='Киргизія' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_ua='Камбоджа' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_ua='Кирібаті' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_ua='Комори' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_ua='Сен-китс і Невіс' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_ua='Північна Корея' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_ua='Південна Корея' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_ua='Кувейт' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_ua='Острови Кайман' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_ua='Казахстан' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_ua='Лаос' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_ua='Ліван' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_ua='Сент-Люсия' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_ua='Ліхтенштейн' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_ua='Шрі-Ланка' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_ua='Ліберія' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_ua='Лесото' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_ua='Литва' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_ua='Люксембург' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_ua='Латвія' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_ua='Лівійська Арабська Джамахирія' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_ua='Марокко' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_ua='Монако' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_ua='Молдова, республіка' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_ua='Мадагаскар' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_ua='Маршаллови Острови' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_ua='Македонія' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_ua='Малі' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_ua='Мьянма' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_ua='Монголія' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_ua='Макао' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_ua='Північні Маріанськіє острови' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_ua='Мартіника' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_ua='Мавританія' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_ua='Монтсеррат' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_ua='Мальта' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_ua='Маврикій' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_ua='Мальдіви' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_ua='Малаві' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_ua='Мексика' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_ua='Малайзія' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_ua='Мозамбік' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_ua='Намібія' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_ua='Нова Каледонія' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_ua='Нігер' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_ua='Острів Норфолк' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_ua='Нігерія' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_ua='Нікарагуа' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_ua='Нідерланди' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_ua='Норвегія' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_ua='Непал' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_ua='Науру' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_ua='Ніуе' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_ua='Нова Зеландія' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_ua='Оман' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_ua='Панама' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_ua='Перу' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_ua='Французька Полінезія' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_ua='Папуа - Нова Гвінея' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_ua='Філіппіни' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_ua='Пакістан' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_ua='Польща' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_ua="Сент-п'єр і Мікелон" WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_ua='Піткерн' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_ua='Пуерто-Ріко' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_ua='Палестинська територія' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_ua='Португалія' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_ua='Палау' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_ua='Парагвай' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_ua='Катар' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_ua='Реюньон' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_ua='Руминія' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_ua='Росія' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_ua='Руанда' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_ua='Саудовская Аравія' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_ua='Соломонови Острови' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_ua='Сейшели' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_ua='Судан' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_ua='Швеція' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_ua='Сінгапур' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_ua='Свята Олена' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_ua='Словенія' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_ua='Шпіцберген і Ян Майен' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_ua='Словакія' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_ua='Сьєрра-Леоне' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_ua='Сан-Маріно' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_ua='Сенегал' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_ua='Сомалі' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_ua='Сурінам' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_ua='Сан-Томе і Принсипи' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_ua='Сальвадор' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_ua='Сірійська Арабська Республіка' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_ua='Свазіленд' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_ua='Острови Теркс і Кайкос' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_ua='Чад' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_ua='Французькі Південні території' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_ua='Того' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_ua='Таїланд' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_ua='Таджикистан' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_ua='Токелау' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_ua='Туркменія' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_ua='Туніс' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_ua='Тонга' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_ua='Східний Тимор' WHERE cn_iso_2='TP';
UPDATE static_countries SET cn_short_ua='Турція' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_ua='Тринідад і Тобаго' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_ua='Тувалу' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_ua='Тайвань (Китай)' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_ua="Танзанія, об'єднана республіка" WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_ua='Україна' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_ua='Уганда' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_ua='Малі Тихоокеанські Віддалені острови США' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_ua='Сполучені Штати' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_ua='Уругвай' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_ua='Узбекістан' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_ua='Ватікан' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_ua='Сент-Вінсент и Гренадини' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_ua='Венесуела' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_ua='Віргінські острови, Британські' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_ua='Віргінські острови, США' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_ua="В'єтнам" WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_ua='Вануату' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_ua='Уолліс і Футуна' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_ua='Самоа' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_ua='Йемен' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_ua='Майотта' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_ua='Югославія' WHERE cn_iso_2='YU';
UPDATE static_countries SET cn_short_ua='Південна Африка' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_ua='Замбія' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_ua='Зімбабве' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_ua='Аландськіє острови' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_ua='Тімор-Лесте' WHERE cn_iso_2='TL';


## static_country_zones
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='AK';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='AZ';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='DE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='DC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='FL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='GA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='GU';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='HI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='ID';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='IL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='IN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='IA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='KS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='KY';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='LA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='MD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='NV';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='NH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='NJ';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='NM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='NY';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='NC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='ND';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='OH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='OK';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='SD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='TX';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='UT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='WV';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='US' AND zn_code='WY';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='AB';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='MB';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='NF';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='NB';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='NS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='ON';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='QC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='SK';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CA' AND zn_code='YT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='NDS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='BAW';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='BAY';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='BER';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='BRG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='BRE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='HAM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='HES';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='MEC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='NRW';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='RHE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='SAR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='SAS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='SAC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='SCN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='DE' AND zn_code='THE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AT' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AT' AND zn_code='OO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AT' AND zn_code='SB';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AT' AND zn_code='KN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AT' AND zn_code='ST';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AT' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AT' AND zn_code='VB';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='AI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='BE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='GL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='JU';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='NW';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='OW';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='SG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='SH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='SZ';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='TG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='UR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='VD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='VS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='ZG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='CH' AND zn_code='ZH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Alava';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Malaga';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Segovia';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Granada';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Jaen';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Sevilla';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Barcelona';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Valencia';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Alicante';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Almeria';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Asturias';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Avila';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Badajoz';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Burgos';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Caceres';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Cadiz';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Cantabria';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Castellon';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Ceuta';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Ciudad Real';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Cordoba';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Cuenca';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Girona';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Las Palmas';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Guadalajara';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Guipuzcoa';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Huelva';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Huesca';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='A CoruГ±a';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='La Rioja';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Leon';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Lugo';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Lleida';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Madrid';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Baleares';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Murcia';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Navarra';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Ourense';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Palencia';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Pontevedra';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Salamanca';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Soria';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Tarragona';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Tenerife';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Teruel';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Toledo';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Valladolid';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Vizcaya';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Zamora';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Zaragoza';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='ES' AND zn_code='Melilla';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='AGS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='BCS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='CAM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='CHIS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='CHIH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='COAH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='COL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='DIF';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='DGO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='GTO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='GRO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='HGO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='JAL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='MEX';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='MICH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='MOR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='NAY';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='NL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='OAX';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='PUE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='QRO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='QROO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='SLP';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='SIN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='SON';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='TAB';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='TAMPS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='TLAX';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='VER';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='YUC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='MX' AND zn_code='ZAC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AU' AND zn_code='ACT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AU' AND zn_code='NSW';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AU' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AU' AND zn_code='QLD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AU' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AU' AND zn_code='TAS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AU' AND zn_code='VIC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='AU' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='AN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='AO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='AQ';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='AT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='AV';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='BG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='BI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='BN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='BO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='BR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='BZ';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='CB';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='CH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='CL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='CN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='CR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='CS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='CZ';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='EN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='FE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='FG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='FI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='FO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='IM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='IS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='KR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='LC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='LE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='LI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='LO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='LT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='MC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='NA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PV';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='PZ';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='RA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='RC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='RE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='RG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='RM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='SI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='SR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='SS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='SV';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='TA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='TE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='TO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='TP';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='TR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='TS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='TV';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='UD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='VC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='VE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='VI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='VP';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='VR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IT' AND zn_code='VV';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='ALD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='ARM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='ATM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='BDS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='BFD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='BIR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='BLG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='BRI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='BRK';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='BRS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='BUX';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CAP';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CAS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CBA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CBE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CER';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CHI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CHS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CLD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CNL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CON';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CTR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='CVE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='DEN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='DFD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='DGL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='DHM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='DOR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='DVN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='DWN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='DYS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='ESX';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='FER';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='FFE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='FLI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='FMH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='GDD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='GLO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='GLR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='GNM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='GNS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='GNW';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='GRN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='GUR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='GWT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='HBS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='HFD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='HLD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='HPH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='HWR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='IOM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='IOW';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='ISL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='JER';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='KNT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='LCN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='LDN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='LDR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='LEC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='LNH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='LTE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='LTM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='LTW';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='MCH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='MER';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='MSY';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='NET';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='NEW';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='NHM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='NLD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='NOR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='NOT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='NWH';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='OFE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='ORK';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='PEM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='PWS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='SCD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='SFD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='SFK';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='SLD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='SOM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='SPE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='SRK';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='SRY';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='SWA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='SXE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='SXW';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='TAF';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='TOR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='TWR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='TYR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='TYS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='VAL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='WIL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='WKS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='WLT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='WMD';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='WRE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='YSN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='YSS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='GB' AND zn_code='YSW';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='CAV';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='CLA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='COR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='DON';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='DUB';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='GAL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='KER';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='KIL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='KLK';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='LAO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='LEI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='LIM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='LOU';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='MAY';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='MEA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='OFF';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='ROS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='SLI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='TIP';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='WAT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='WES';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='WEX';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='IE' AND zn_code='WIC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='AC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='AM';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='DF';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='ES';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='MG';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='PB';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='RJ';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='RR';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='RS';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='SE';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_ua='' WHERE zn_country_iso_2='BR' AND zn_code='TO';


## static_currencies
UPDATE static_currencies SET cu_name_ua='Дирхам (ОАЭ)',cu_sub_name_ua='' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_ua='Лек',cu_sub_name_ua='' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_ua='Вірменський драм',cu_sub_name_ua='' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_ua='Нідерландський антільський гульден',cu_sub_name_ua='' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_ua='Кванза',cu_sub_name_ua='' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_ua='Аргентинске песо',cu_sub_name_ua='' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_ua='Австралійський долар',cu_sub_name_ua='' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_ua='Арубанській гульден',cu_sub_name_ua='' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_ua='Азербайджанський манат',cu_sub_name_ua='' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_ua='Боснійська марка',cu_sub_name_ua='' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_ua='Барбадосский долар',cu_sub_name_ua='' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_ua='Така',cu_sub_name_ua='' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_ua='Болгарский лев',cu_sub_name_ua='' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_ua='Бахрейнській динар',cu_sub_name_ua='' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_ua='Бурундійській франк',cu_sub_name_ua='' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_ua='Бермудський долар',cu_sub_name_ua='' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_ua='Брунейский долар',cu_sub_name_ua='' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_ua='Боливиано',cu_sub_name_ua='' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_ua='Бразильський реал',cu_sub_name_ua='' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_ua='Багамський долар',cu_sub_name_ua='' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_ua='Нгултрум',cu_sub_name_ua='' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_ua='Пула',cu_sub_name_ua='' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_ua='Білоруський рубель',cu_sub_name_ua='' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_ua='Белізській долар',cu_sub_name_ua='' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_ua='Канадський долар',cu_sub_name_ua='' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_ua='Конголезький франк',cu_sub_name_ua='' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_ua='Швейцарський франк',cu_sub_name_ua='' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_ua='Чилійське песо',cu_sub_name_ua='' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_ua='Юань Ренминби',cu_sub_name_ua='' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_ua='Колумбійське песо',cu_sub_name_ua='' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_ua='Костаріканський колон',cu_sub_name_ua='' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_ua='Кубинське песо',cu_sub_name_ua='' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_ua='Ескудо Кабо-верде',cu_sub_name_ua='' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_ua='Кіпрский фунт',cu_sub_name_ua='' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_ua='Чеська крона',cu_sub_name_ua='' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_ua='Франк Джібуті',cu_sub_name_ua='' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_ua='Данська крона',cu_sub_name_ua='' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_ua='Домініканське песо',cu_sub_name_ua='' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_ua='Алжірський динар',cu_sub_name_ua='' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_ua='Естонська крона',cu_sub_name_ua='' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_ua='Єгипетський фунт',cu_sub_name_ua='' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_ua='Накфа',cu_sub_name_ua='' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_ua='Ефіопський бир',cu_sub_name_ua='' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_ua='Євро',cu_sub_name_ua='' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_ua='Долар Фіджі',cu_sub_name_ua='' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_ua='Фунт Фолклендських островів',cu_sub_name_ua='' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_ua='Фунт стерлінгів',cu_sub_name_ua='' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_ua='Ларі',cu_sub_name_ua='' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_ua='Седи',cu_sub_name_ua='' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_ua='Гібралтарський фунт',cu_sub_name_ua='' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_ua='Даласі',cu_sub_name_ua='' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_ua='Гвінейський франк',cu_sub_name_ua='' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_ua='Кетсаль',cu_sub_name_ua='' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_ua='Песо Гвінеї-Бісау',cu_sub_name_ua='' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_ua='Гайанській долар',cu_sub_name_ua='' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_ua='Гонконгский долдар',cu_sub_name_ua='' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_ua='Лемпира',cu_sub_name_ua='' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_ua='Куна',cu_sub_name_ua='' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_ua='Гурд',cu_sub_name_ua='' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_ua='Форинт',cu_sub_name_ua='' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_ua='Рупия',cu_sub_name_ua='' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_ua='Новий ізраїльський шекель',cu_sub_name_ua='' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_ua='Індійська рупія',cu_sub_name_ua='' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_ua='Іракский дінар',cu_sub_name_ua='' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_ua='Іранский ріал',cu_sub_name_ua='' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_ua='Ісландська крона',cu_sub_name_ua='' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_ua='Ямайський долар',cu_sub_name_ua='' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_ua='Йорданський динар',cu_sub_name_ua='' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_ua='Йена',cu_sub_name_ua='' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_ua='Кенійський шилінг',cu_sub_name_ua='' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_ua='Сом',cu_sub_name_ua='' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_ua='Риель',cu_sub_name_ua='' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_ua='Франк Коморськіх островів',cu_sub_name_ua='' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_ua='Північно-корейська вона',cu_sub_name_ua='' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_ua='Вона',cu_sub_name_ua='' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_ua='Кувейтський динар',cu_sub_name_ua='' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_ua='Долар Кайманових островів',cu_sub_name_ua='' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_ua='Тенге',cu_sub_name_ua='' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_ua='Кіп',cu_sub_name_ua='' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_ua='Ліванский фунт',cu_sub_name_ua='' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_ua='Шрі-Ланкійський рупій',cu_sub_name_ua='' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_ua='Ліберійський долар',cu_sub_name_ua='' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_ua='Лоти',cu_sub_name_ua='' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_ua='Литовский літ',cu_sub_name_ua='' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_ua='Латвійські лати',cu_sub_name_ua='' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_ua='Лівійський динар',cu_sub_name_ua='' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_ua='Марокканский дирхам',cu_sub_name_ua='' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_ua='Молдавский лей',cu_sub_name_ua='' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_ua='Дінар',cu_sub_name_ua='' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_ua='Кьят',cu_sub_name_ua='' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_ua='Тугрик',cu_sub_name_ua='' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_ua='Патака',cu_sub_name_ua='' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_ua='Угия',cu_sub_name_ua='' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_ua='Мальтійська ліра',cu_sub_name_ua='' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_ua='Маврікийськая рупія',cu_sub_name_ua='' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_ua='Руфія',cu_sub_name_ua='' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_ua='Квача',cu_sub_name_ua='' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_ua='Мексиканське песо',cu_sub_name_ua='' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_ua='Малайзійський рингтит',cu_sub_name_ua='' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_ua='Метікал',cu_sub_name_ua='' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_ua='Долар Намібії',cu_sub_name_ua='' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_ua='Найра',cu_sub_name_ua='' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_ua='Золота кордоба',cu_sub_name_ua='' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_ua='Норвезька крона',cu_sub_name_ua='' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_ua='Непальський рупій',cu_sub_name_ua='' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_ua='Новозеландський долар',cu_sub_name_ua='' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_ua='Оманский ріал',cu_sub_name_ua='' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_ua='Бальбоа',cu_sub_name_ua='' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_ua='Новий соль',cu_sub_name_ua='' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_ua='Кина',cu_sub_name_ua='' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_ua='Філіппінське песо',cu_sub_name_ua='' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_ua='Пакистанський рупій',cu_sub_name_ua='' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_ua='Злотий',cu_sub_name_ua='' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_ua='Гуарани',cu_sub_name_ua='' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_ua='Катарский ріал',cu_sub_name_ua='' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_ua='Лей',cu_sub_name_ua='' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_ua='Російський рубель',cu_sub_name_ua='' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_ua='Франк Руанди',cu_sub_name_ua='' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_ua='Саудівський риял',cu_sub_name_ua='' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_ua='Долар Соломонових островів',cu_sub_name_ua='' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_ua='Сейшельський рупій',cu_sub_name_ua='' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_ua='Суданский динар',cu_sub_name_ua='' WHERE cu_iso_3='SDD';
UPDATE static_currencies SET cu_name_ua='Шведська крона',cu_sub_name_ua='' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_ua='Сінгапурський долар',cu_sub_name_ua='' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_ua='Фунт Острова Святої Олени',cu_sub_name_ua='' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_ua='Толар',cu_sub_name_ua='' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_ua='Словацька крона',cu_sub_name_ua='' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_ua='Леоні',cu_sub_name_ua='' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_ua='Шилінг, Сомалі',cu_sub_name_ua='' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_ua='Добра',cu_sub_name_ua='' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_ua='Сальвадорський колон',cu_sub_name_ua='' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_ua='Сірійський фунт',cu_sub_name_ua='' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_ua='Лілангені',cu_sub_name_ua='' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_ua='Бат',cu_sub_name_ua='' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_ua='Сомоні',cu_sub_name_ua='' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_ua='Манат',cu_sub_name_ua='' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_ua='Туніський динар',cu_sub_name_ua='' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_ua='Паанга',cu_sub_name_ua='' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_ua='Долар Тринідаду і Тобаго',cu_sub_name_ua='' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_ua='Новий тайваньський долар',cu_sub_name_ua='' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_ua='Танзанийский шилінг',cu_sub_name_ua='' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_ua='Гривня',cu_sub_name_ua='' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_ua='Угандийский шилінг',cu_sub_name_ua='' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_ua='Долар США',cu_sub_name_ua='' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_ua='Уругвайське песо',cu_sub_name_ua='' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_ua='Узбецький сум',cu_sub_name_ua='' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_ua='Болівар',cu_sub_name_ua='' WHERE cu_iso_3='VEB';
UPDATE static_currencies SET cu_name_ua='Донг',cu_sub_name_ua='' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_ua='Вату',cu_sub_name_ua='' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_ua='Тала',cu_sub_name_ua='' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_ua='Франк КФА ВЕАС',cu_sub_name_ua='' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_ua='Східно-карибський долар',cu_sub_name_ua='' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_ua='Франк КФА ВСЕАО',cu_sub_name_ua='' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_ua='Франк КФП',cu_sub_name_ua='' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_ua='Йеменський ріал',cu_sub_name_ua='' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_ua='Ренд',cu_sub_name_ua='' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_ua='Квача (замбийская)',cu_sub_name_ua='' WHERE cu_iso_3='ZMK';
UPDATE static_currencies SET cu_name_ua='Долар Зімбабве',cu_sub_name_ua='' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_ua='Афгани',cu_sub_name_ua='' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_ua='Сербский динар',cu_sub_name_ua='' WHERE cu_iso_3='CSD';
UPDATE static_currencies SET cu_name_ua='Франк, Малаги',cu_sub_name_ua='' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_ua='Суринамский долар',cu_sub_name_ua='' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_ua='Турецка ліра',cu_sub_name_ua='' WHERE cu_iso_3='TRY';


## static_languages
UPDATE static_languages SET lg_name_ua='Абхазька' WHERE lg_iso_2='AB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Афар' WHERE lg_iso_2='AA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Африкаанс' WHERE lg_iso_2='AF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Албанська' WHERE lg_iso_2='SQ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Амхарська' WHERE lg_iso_2='AM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Арабська' WHERE lg_iso_2='AR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Вірменська' WHERE lg_iso_2='HY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Асамська' WHERE lg_iso_2='AS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Аймара' WHERE lg_iso_2='AY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Азербайджанська' WHERE lg_iso_2='AZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Башкірська' WHERE lg_iso_2='BA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Баська' WHERE lg_iso_2='EU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Бенгальська' WHERE lg_iso_2='BN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Дзонг-ке' WHERE lg_iso_2='DZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Біхарська' WHERE lg_iso_2='BH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Бісламська' WHERE lg_iso_2='BI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Бретонська' WHERE lg_iso_2='BR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Болгарська' WHERE lg_iso_2='BG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Бырманська' WHERE lg_iso_2='MY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Білоруська' WHERE lg_iso_2='BE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Кхмерська' WHERE lg_iso_2='KM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Каталонська' WHERE lg_iso_2='CA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Чжуаньська' WHERE lg_iso_2='ZA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Китайська' WHERE lg_iso_2='ZH' AND lg_country_iso_2='HK';
UPDATE static_languages SET lg_name_ua='Корсіканська' WHERE lg_iso_2='CO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Хорватська' WHERE lg_iso_2='HR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Чеська' WHERE lg_iso_2='CS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Данська' WHERE lg_iso_2='DA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Нідерландська' WHERE lg_iso_2='NL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Англійська' WHERE lg_iso_2='EN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Есперанто' WHERE lg_iso_2='EO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Естонська' WHERE lg_iso_2='ET' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Фарерська' WHERE lg_iso_2='FO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Персидська' WHERE lg_iso_2='FA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Фіджі' WHERE lg_iso_2='FJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Фінська' WHERE lg_iso_2='FI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Французька' WHERE lg_iso_2='FR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Фризька' WHERE lg_iso_2='FY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Галісийська' WHERE lg_iso_2='GL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Шотландська' WHERE lg_iso_2='GD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Менська' WHERE lg_iso_2='GV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Грузинська' WHERE lg_iso_2='KA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Німецька' WHERE lg_iso_2='DE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Грецька' WHERE lg_iso_2='EL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Калмицька' WHERE lg_iso_2='KL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Гуаранська' WHERE lg_iso_2='GN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Гуджаратійська' WHERE lg_iso_2='GU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Хауса' WHERE lg_iso_2='HA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Іврит' WHERE lg_iso_2='HE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Хінді' WHERE lg_iso_2='HI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Венгерська' WHERE lg_iso_2='HU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Ісландська' WHERE lg_iso_2='IS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Індонезійська' WHERE lg_iso_2='ID' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Інуктітут' WHERE lg_iso_2='IU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Інупіак' WHERE lg_iso_2='IK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Ірландська' WHERE lg_iso_2='GA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Італійська' WHERE lg_iso_2='IT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Японська' WHERE lg_iso_2='JA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Каннада' WHERE lg_iso_2='KN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Кашмірі' WHERE lg_iso_2='KS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Казахська' WHERE lg_iso_2='KK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Киньяруанда' WHERE lg_iso_2='RW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Киргизька' WHERE lg_iso_2='KY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Рунді' WHERE lg_iso_2='RN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Корейська' WHERE lg_iso_2='KO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Курдська' WHERE lg_iso_2='KU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Лаосский' WHERE lg_iso_2='LO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Латиська' WHERE lg_iso_2='LV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Лінгала' WHERE lg_iso_2='LN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Литовська' WHERE lg_iso_2='LT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Македонська' WHERE lg_iso_2='MK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Малага' WHERE lg_iso_2='MG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Малайська' WHERE lg_iso_2='MS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Малаялям' WHERE lg_iso_2='ML' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Мальтійська' WHERE lg_iso_2='MT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Маорі' WHERE lg_iso_2='MI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Маратхі' WHERE lg_iso_2='MR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Молдавська' WHERE lg_iso_2='MO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Монгольська' WHERE lg_iso_2='MN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Науру' WHERE lg_iso_2='NA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Непальська' WHERE lg_iso_2='NE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Норвежська' WHERE lg_iso_2='NO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Окситанська' WHERE lg_iso_2='OC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Орія' WHERE lg_iso_2='OR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Оромо' WHERE lg_iso_2='OM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Пушту' WHERE lg_iso_2='PS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Польська' WHERE lg_iso_2='PL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Португальська' WHERE lg_iso_2='PT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Панджаби' WHERE lg_iso_2='PA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Кечуа' WHERE lg_iso_2='QU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Ретороманська' WHERE lg_iso_2='RM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Румунська' WHERE lg_iso_2='RO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Російська' WHERE lg_iso_2='RU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Самоанська' WHERE lg_iso_2='SM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Санго' WHERE lg_iso_2='SG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Сербська' WHERE lg_iso_2='SR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Сото Південний' WHERE lg_iso_2='ST' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Тсвана' WHERE lg_iso_2='TN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Шона' WHERE lg_iso_2='SN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Синдхи' WHERE lg_iso_2='SD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Сингальська' WHERE lg_iso_2='SI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Свази' WHERE lg_iso_2='SS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Словацька' WHERE lg_iso_2='SK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Словенська' WHERE lg_iso_2='SL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Сомалі' WHERE lg_iso_2='SO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Іспанська' WHERE lg_iso_2='ES' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Сунданська' WHERE lg_iso_2='SU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Суахілі' WHERE lg_iso_2='SW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Шведська' WHERE lg_iso_2='SV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Тагальська' WHERE lg_iso_2='TL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Таджицька' WHERE lg_iso_2='TG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Тамільська' WHERE lg_iso_2='TA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Татарська' WHERE lg_iso_2='TT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Телугу' WHERE lg_iso_2='TE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Тайська' WHERE lg_iso_2='TH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Тибет' WHERE lg_iso_2='BO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Тігрінья' WHERE lg_iso_2='TI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Тонга (Тонга Ісландська)' WHERE lg_iso_2='TO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Тсонга' WHERE lg_iso_2='TS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Турецька' WHERE lg_iso_2='TR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Туркменська' WHERE lg_iso_2='TK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Тві' WHERE lg_iso_2='TW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Уйгурська' WHERE lg_iso_2='UG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Українська' WHERE lg_iso_2='UK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Урду' WHERE lg_iso_2='UR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Узбецька' WHERE lg_iso_2='UZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua="В'єтнамська" WHERE lg_iso_2='VI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Валлійська (Уельська)' WHERE lg_iso_2='CY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Волоф' WHERE lg_iso_2='WO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Коса' WHERE lg_iso_2='XH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Йоруба' WHERE lg_iso_2='YO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Зулу' WHERE lg_iso_2='ZU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Боснійська' WHERE lg_iso_2='BS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Акан' WHERE lg_iso_2='AK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Арагонська' WHERE lg_iso_2='AN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Аварська' WHERE lg_iso_2='AV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Бамбара' WHERE lg_iso_2='BM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Чеченська' WHERE lg_iso_2='CE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Чаморро' WHERE lg_iso_2='CH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Крі' WHERE lg_iso_2='CR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Чуваська' WHERE lg_iso_2='CV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Дівехи (Мальдівська)' WHERE lg_iso_2='DV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Еве' WHERE lg_iso_2='EE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Фулах' WHERE lg_iso_2='FF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Хирімоту' WHERE lg_iso_2='HO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Гаїтянська' WHERE lg_iso_2='HT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Гереро' WHERE lg_iso_2='HZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Ігбо' WHERE lg_iso_2='IG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Сичуань' WHERE lg_iso_2='II' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Конго' WHERE lg_iso_2='KG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Кикуйю' WHERE lg_iso_2='KI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Киньяма' WHERE lg_iso_2='KJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Канурі' WHERE lg_iso_2='KR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Комі' WHERE lg_iso_2='KV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Корнська' WHERE lg_iso_2='KW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Люксембурзька' WHERE lg_iso_2='LB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Ганда' WHERE lg_iso_2='LG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Лімбургийська' WHERE lg_iso_2='LI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Луба-Катанга' WHERE lg_iso_2='LU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Маршальська' WHERE lg_iso_2='MH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Норвезька бокмол' WHERE lg_iso_2='NB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Ндебеле північна' WHERE lg_iso_2='ND' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Ндунга' WHERE lg_iso_2='NG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Нюнорська (Новонорвежська)' WHERE lg_iso_2='NN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Ндебеле південна' WHERE lg_iso_2='NR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Навахо' WHERE lg_iso_2='NV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Ньянджа' WHERE lg_iso_2='NY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Оджібва' WHERE lg_iso_2='OJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Осетинська' WHERE lg_iso_2='OS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Сардінська' WHERE lg_iso_2='SC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Північно-саамська' WHERE lg_iso_2='SE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Таітянська' WHERE lg_iso_2='TY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Венда' WHERE lg_iso_2='VE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Валлонська' WHERE lg_iso_2='WA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Яванецька' WHERE lg_iso_2='JV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Португальська' WHERE lg_iso_2='PT' AND lg_country_iso_2='BR';
UPDATE static_languages SET lg_name_ua='Китайська' WHERE lg_iso_2='ZH' AND lg_country_iso_2='CN';
UPDATE static_languages SET lg_name_ua='Інтерлінгва' WHERE lg_iso_2='IA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Інтерлінгве' WHERE lg_iso_2='IE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Латинська' WHERE lg_iso_2='LA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Санскрит' WHERE lg_iso_2='SA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Волапюк' WHERE lg_iso_2='VO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Ідиш' WHERE lg_iso_2='YI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Авестійська' WHERE lg_iso_2='AE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua="Церковно-слов 'янська" WHERE lg_iso_2='CU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Ідо' WHERE lg_iso_2='IO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ua='Пали' WHERE lg_iso_2='PI' AND lg_country_iso_2='';
